### PR TITLE
Load .mbedignore from project root directory

### PR DESCRIPTION
**Pull request by KKoovalsky**
# Description

If `.mbedignore` is present in the root directory of the project, it will be applied to the build.

The `.mbedignore` supports [official file format](https://os.mbed.com/docs/mbed-os/v6.14/program-setup/build-rules.html#mbedignore). Moreover, the `.mbedignore` files used within a pure `mbed` project (without `pio`), can be used without changes as well.

Additionally, to prevent from confusion, other patterns prefixes are supported too:

```
mbed-os/features/cellular/*
framework-mbed/features/cellular/*
features/cellular/*
``` 

are equivalent and will result in excluding:

```
features/cellular/*
```
The following commit messages explain more details:
* https://github.com/platformio/builder-framework-mbed/commit/8ca976f30b6857844b0bf33287503d3370e9b324 
* https://github.com/platformio/builder-framework-mbed/commit/68f470bafd278925abd66fa433dcc2023a9352b1

# Background

This solution came out from [this forum post](https://community.platformio.org/t/eager-to-implement-handling-of-mbedignore-within-pio/23735/2). Maximilian Gerhardt suggested to use `self.ignore_dirs` to implement that feature. Unfortunately, there is a [bug in MBED's build API](https://github.com/ARMmbed/mbed-os/issues/15125).

### CODE REVIEW

**Comment by KKoovalsky** [comment]
Is there a reason why those lines:

```
mbed-os/TEST_APPS/*
mbed-os/TESTS/*
mbed-os/UNITTESTS/*
```
Do appear in the `.mbedignore`? I guess those files will not be compiled during `pio run` anyway?

**Comment by KKoovalsky** [comment]
You are completely right in this comment https://github.com/platformio/builder-framework-mbed/pull/26#issuecomment-933312503. 
I was asking for the directories:
```
mbed-os/TEST_APPS/*
mbed-os/TESTS/*
mbed-os/UNITTESTS/*
```
To find out whether removal of lines with `*` is sufficient, or whether we should apply different logic for the directories ignored at the first level of the directory tree of the MBED framework.

**Comment by KKoovalsky** [comment]
@Copper-Bot 
> Well, I think the best thing to do is to describe the ignore path from the framework root folder, and not from his subfolders.
That would be cool, but unfortunately it is hard to implement. The problem is that the MBED API asks whether the relative path is ignored. So the query parameter for `is_ignored` is, e.g. `source/TARGET_CORTEX/rtx5/Include/cmsis_os2.h` for the file `rtos/source/TARGET_CORTEX/rtx5/Include/cmsis_os2.h`. The API cuts the first folder name on its own.

> That could resolve a lot of things, especially if there are two sub-subfolders with the same name, but with different parent folder name.
Is it often that folder paths overlap and if yes, is the workaround, to specify more `.mbedignore` paths, fixing it? Let's say, the directory tree looks like that:
```
a/b/c/d --- 1 # To be ignored
          | --- 2 # To be ignored
b/c/d --- 3 # Must stay
       | --- 4 # To be ignored
```
Then the workaround would be to put to the `.mbedignore`:
```
a/b/c/d/1/*
a/b/c/d/2/*
b/c/d/4/*
```

One more thing: https://os.mbed.com/blog/entry/Introducing-the-new-Mbed-Tools/. It has been mentioned in the answer to the issue I have raised in MBED OS: https://github.com/ARMmbed/mbed-os/issues/15125#issuecomment-933231426.

Collecting all that, my suggestion is to fix the issue related to pattern "*" that is applied when the user wants to ignore contents of first-level subdirectory (the one explained here: https://github.com/platformio/builder-framework-mbed/pull/26#issuecomment-933312503). If the old mbed-tools are going to be abandoned, let's keep this improvement simple, document what is supported and what is not supported, and swallow the limitations. I guess most cases will be covered with the PR in such a form.

**Comment by KKoovalsky** [comment]
Yes, most probably you are right. Could you send your `.mbedignore`?

**Comment by KKoovalsky** [comment]
@Copper-Bot I can see that you are quite handy with the code. Could I ask you to add line:

```
print(self._ignore_patterns)
```
below that line:
https://github.com/platformio/builder-framework-mbed/pull/26/files#diff-d5c2212e2381df5ec71acb92b8a3a56b0af7e54ca57b63729a54f09f306e8808R51

And run:

```
pio run -t clean && pio run
```
and upload the output? :)

**Comment by valeros** [comment]
Hi guys, thanks for the PR and valuable discussion. If I recall correctly the Mbed build API v1 is no longer recommended for new designs as the Mbed OS project is being gradually (if not already) switched to CMake as their main build system (even though it's still in beta). Long story short, I'm afraid we will need to completely refactor the PlatformIO build script for Mbed in order to use CMake as the source of build information (source files, build flags. etc.), so I believe the current implementation will undergo significant changes. What's even more complicates the matter is that PlatformIO also supports Mbed v5 which depends on the legacy tools, so will need to give much thought on how to properly implement build scripts for the future releases of Mbed.

**Comment by KKoovalsky** [comment]
@valeros Are there plans for `pio` to switch to CMake as well? That would simplify supporting other libraries, I guess.

Does it mean that this PR is not going to be reviewed and possibly merged?

**Comment by valeros** [comment]
Hi @KKoovalsky! Yes, we plan to use CMake once we have spare time to refactor build scripts and integrate new releases of Mbed. Hopefully, this will also resolve a long-standing issue with the current build workflow when all framework source files are compiled regardless of what features are used in a project. We really appreciate the work you've done here, I can review and even merge the PR, but what's the point if it won't land in the next release of the PlatformIO build scripts for Mbed?

**Comment by KKoovalsky** [comment]
I see. I agree then, I don't want to take your time for something what may be killed soon.

**Pull request closed without merging**
