### PR TITLE
bugfix: was not working in python3.9

### PR DESCRIPTION
**Pull request by SubaruArai**
the version of intelhex was too old.

issue: #22

### CODE REVIEW

**Comment by valeros** [comment]
Hi @SubaruArai ! This problem was already resolved some time ago, but the changes wasn't mirrored in this repository. Have you bumped into any issues with Python 3.9 lately?

**Comment by SubaruArai** [comment]
@valeros Thank you, I didn't expect such a fast response!

Yes, I did encounter it. Here are my environments:

- OS: windows 10 2004 (confirmed on 1903 too)
- IDE: VSCode(1.58.2)

Here are my steps to reproduce:

1. install platformio from the Extensions tab
2. start a new project using the following config:
    - board = nucleo_f303k8
    - framework = mbed
3. see error occur

or, after the generation:

1. cd into that generated folder
2. pio run
3. see error occur, ending with
```
  File "C:\Users\someone\.platformio\packages\framework-mbed\platformio\package_deps\py3\intelhex\compat.py", line 60:
    array_tobytes = getattr(array.array, "tobytes", array.array.tostring)
```

**Comment by valeros** [comment]
That's strange, but I cannot reproduce the problem on Python 3.9.4. What version of the `ststm32` platform is installed in your system? Could you please attach the entire log when you're trying to compile?

**Comment by SubaruArai** [comment]
@valeros 
After your response I tried a few things and I think I found the root cause.

1. Turns out the `ststm32` version was quite old, `8.0.0` on both platforms that I tested, which seemed to be the root cause.
    - the version of `framework-mbed` tied was `6.60200.200722`, which contained the problem.
3. Updating `ststm32` to `14.1.0` fixed it, `pio run` showed using `framework-mbed 6.60900.210318`.
4. After clean reinstalling platformio (also deleting ~/.platformio), the issue disappeared, using `ststm32@14.1.0`.

So, it was a problem of me using a too old library. My bad, and thank you for your fast response and patience!

**Pull request closed without merging**
